#!/bin/bash

function command_auto-update {

	function help {

		echo -e "  Update Pulsion script to the latest version available on bitbucket master branch"
		echo -e "  Usage : auto-update"

	}

	function process {

		# Call like that fix : http://stackoverflow.com/questions/4754592/could-replacing-a-bash-script-with-a-new-version-cause-a-running-instance-of-the
		"pulsion/get_pulsion" > pulsion/pulsion.update
		cat pulsion/pulsion.update | bash

	}

}
