#!/bin/bash

function command_auto-update {

	function help {

		echo -e "  Update Pulsion script to the latest version available on bitbucket master branch"
		echo -e "  Usage : auto-update"

	}

	function process {

		"pulsion/get_pulsion" > pulsion/pulsion.update
		cat pulsion/pulsion.update | bash

	}

}
