#!/bin/bash

function ensure_command_exist {

	if is_function_exist $1; then
		verbose 1 "- \"$1\" function implementation does not exist"
		exit 1
	fi;

}

# Gère le lecture des paramètres passés à la console
function interpret_command_line {

	command_set=0
	help_mode=0
	initial_params="$@"

	while test $# -gt 0
	do
	        case "$1" in

	                -c)		# Path to configuration file
	                        shift
	                        if test $# -gt 0; then
	                                CONFIG_FILE=$1
	                        else
	                                echo "-c option wait a config file path"
	                                exit 1
	                        fi
	                        shift
	                        ;;

	                -v)		# Level du mode verbose
							shift
							VERBOSE=$1
							shift
							;;

					--help*) # Display help for one command
							ACTION="help $initial_params"
							break
							;;

					-h)
							ACTION="help $initial_params"
							break
							;;

	                *)		# Concatène la commande et les paramètres
							if [ $command_set -eq 0 ]; then
								COMMAND=$1
								command_set=1
							else
								ACTION="$ACTION $1"
							fi
	                        shift
	                        ;;

	        esac

	done

	COMMAND="command_$COMMAND"

	ensure_command_exist


}
