#!/bin/bash

FORWARDED=1

# Gère le lecture des paramètres passés à la console
function interpret_command_line {
	if [[ $1 == *"::"* ]]; then
		forward_command "$@"
		FORWARDED=0
	else
		execute_command "$@"
		FORWARDED=1
	fi
}

# Execution of command require to forward command to an imported pulsion project
function forward_command {
	IFS=':'
	read -r sub_pulsion_project_name rest <<< "$@"
	IFS=' '
	read -r cmd useless <<< "$rest"

	if get_import_path "$sub_pulsion_project_name" false; then
		path="$(get_import_path "$sub_pulsion_project_name" true)"
	else
		return 1
	fi

	shift
	cd "$path" > /dev/null
	./pulsion/pulsion "${cmd:1}" "$@"
	cd - > /dev/null
}

# Execute the command
function execute_command {
	command_set=0
	help_mode=0
	initial_params="$@"

	while test $# -gt 0
	do
	        case "$1" in

	                -c)		# Path to configuration file
	                        shift
	                        ## Already process in launcher load_config_file
	                        shift
	                        ;;

	                -v)		# Level du mode verbose (print)
							shift
							VERBOSE=$1
							shift
							;;

					--help*) # Display help for one command
							ACTION="help $initial_params"
							break
							;;

					-h)
							ACTION="help $initial_params"
							break
							;;

	                *)		# Concatène la commande et les paramètres
							if [ $command_set -eq 0 ]; then
								COMMAND=$1
								command_set=1
							else
								ACTION="$ACTION $1"
							fi
	                        shift
	                        ;;

	        esac

	done

	COMMAND="command_$COMMAND"

}

function is_forwarded {
	return $FORWARDED
}
