#!/bin/bash

function launch_framework {

	# Use sudo for install
	#if ! is_root; then
	#	echo "Usage : sudo scripts/console"
	#	exit 1
	#fi

	# Set the environment variables with parameters
	overload_environment_variables "$@"

	# Load configuration file
	if [ -f $CONFIG_FILE ]; then
		verbose 3 "- Load the default configuration script: $CONFIG_FILE"
		source $CONFIG_FILE
	else
		verbose 1 "- Invalid configuration file: $CONFIG_FILE"
		exit 1
	fi

	# Verify existance and launch $command
	if ! type -t $COMMAND | grep -q "^function$" ; then

		verbose 1 "- \"$COMMAND\" function implementation does not exist"
		exit 1

	fi

	$COMMAND
	$ACTION

}
