#!/bin/bash

function load_config_file {

	if has_param -c "$@"; then
		CONFIG_FILE="$(get_param_value -c "$@")"
	fi

	if [ -f $CONFIG_FILE ]; then
		verbose 3 "- Load the default configuration script: $CONFIG_FILE"
		source $CONFIG_FILE
	else
		verbose 1 "- Invalid configuration file: $CONFIG_FILE"
		exit 1
	fi

}

function launch_framework {

	# Load configuration file
	load_config_file "$@"

	# Import child pulsion projects
	load_imports

	# Parse the command line parameters
	interpret_command_line "$@"

	if ! is_forwarded "$@"; then

		if ! is_function_exist $COMMAND; then
			verbose 1 "- \"$1\" function implementation does not exist"
			exit 1
		fi;

		$COMMAND
		$ACTION

	fi

}
