#!/bin/bash

function check_config_file {

	if [ -f $CONFIG_FILE ]; then
		verbose 3 "- Load the default configuration script: $CONFIG_FILE"
		source $CONFIG_FILE
	else
		verbose 1 "- Invalid configuration file: $CONFIG_FILE"
		exit 1
	fi

}

function launch_framework {

	# Parse the command line parameters
	interpret_command_line "$@"

	# Load configuration file
	check_config_file

	$COMMAND
	$ACTION

}
