#!/bin/bash

# Pulsion console
#
# All users scripts are in the config pulsion file
# Usage : ./pulsion/pulsion
# Default config pulsion file parameter is set to pulsion/config_pulsion
#

. project/environment_variables #include
. project/helpers #include
. project/import #include
. project/interpreter #include
. project/launcher #include

. project/command/command_default #include
. project/command/command_auto-update #include
. project/command/command_list #include

# Launch the console
launch_framework "$@"
