#!/bin/bash

if ! [ -f "pulsion/get_pulsion" ]; then
	echo "You must run the script get_pulsion from project root."
	exit 1
fi

# Environment variables
INSTALL_PATH="$(pwd)/pulsion"
TEMPORARY_FOLDER_ROOT="pulsion/tmp"
TEMPORARY_FOLDER="$TEMPORARY_FOLDER_ROOT/get_pulsion_compile/$RANDOM"

# Select branch to import
branch="open-source"
if [ $# -eq 1 ]; then
	branch="$1"
fi

# Clone in temporary folder
mkdir -p $TEMPORARY_FOLDER
cd $TEMPORARY_FOLDER
git clone https://github.com/jeremieca/pulsion.git
cd pulsion
git checkout $branch

# Fusion and copy
./project/pulsion fusion -t --local
if [ -f output/pulsion ]; then
	cp output/pulsion $INSTALL_PATH
	chmod +x $INSTALL_PATH/pulsion
	cd "$INSTALL_PATH/.."
	rm -Rf $TEMPORARY_FOLDER_ROOT
	if [[ $branch == "open-source" ]]; then
		echo "You have now the latest stable version of Pulsion"
	else
		echo "You have now the latest version of Pulsion in $branch"
	fi

else
	echo "Get Pulsion failed"
fi
