#!/bin/bash

function command_hello {

	function help {

		echo "Hello world !"

	}

	function process {

		echo "Hello world !"

	}

}

function command_parameters {

	function help {

		echo "Usage : parameters"

	}

	function process {

		#the test parameters : --force lol -t ok -o

		# Must display "ok"
		if has_param -t "$@"; then
			get_param_value -t "$@"
		fi

		# Must display nothing
		if has_param -o "$@"; then
			get_param_value -o "$@"
		fi

	}

}
