#!/bin/bash

function command_hello {

	function help {

		echo "Hello world !"

	}

	function process {

		echo "Hello world !"

	}

}

function command_parameters {

	function help {

		echo "Usage : parameters"

	}

	function process {

		#the test parameters : --force lol -t ok -o

		# Must display "ok"
		if has_param -t "$@"; then
			get_param_value -t "$@"
		fi

		# Must display nothing
		if has_param -o "$@"; then
			get_param_value -o "$@"
		fi

	}

}

function command_stream {

	function help {

		echo "Basic test of streams"

	}

	function process {

		stream::print 1 echo "yes"
		stream::print 2 echo "no"

	}

}

function command_streamfilter {

	function help {

		echo "Stream filter"

	}

	function process {

		function whendone {
			echo "$1 done"
		}

		stream::action whendone \
			stream::filter *"mongoose"* \
				echo "super mongoose"

		stream::action whendone \
			stream::filter *"mongoose"* \
				echo "super filter"

	}

}
